<!DOCTYPE html>
<html>
  <head>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    
	<style type="text/css">
      body { background-color:#DDD; }
      [class*="col"] { margin-bottom: 20px; }
      img { width: 100%; }
      .well {
        background-color:#CCC;
        padding: 20px;
      }
      .inline-form input {
            display: inline-block;
            width: 100px;
        }	
    </style>
  </head>
  <body>

<div class="container">

<nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <ul class="nav navbar-nav">
            <li > <a href="../accueil/">Accueil</a> </li>
            <li> <a href="../add_delete/">Ajout/Suppression de voiture</a> </li>
            <li class="active"> <a href="">Garage</a> </li>
            
          </ul>
          
        </div>
      </nav>

<header class="page-header">
        <h1>Actuellement dans notre garage</h1>
      </header>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Les marques :</h3>
  </div>
    <div class="list-group">
      <a href="#" class="list-group-item">
        Ferrari
        <span class="badge">148</span>
      </a>
      <a href="#" class="list-group-item">
        Lamborghini
         <span class="badge">38</span>
       </a>
       <a href="#" class="list-group-item">
         Alpha Romeo
         <span class="badge">122</span>
       </a>
       <a href="#" class="list-group-item">
         Aston Martin
         <span class="badge">97</span>
       </a>
       <a href="#" class="list-group-item">
          Porsche
          <span class="badge">837</span>
        </a>
       <a href="#" class="list-group-item">
          Audi
         <span class="badge">420</span>
       </a>
       <a href="#" class="list-group-item">
          Mercedes
          <span class="badge">58</span>
       </a>
       <a href="#" class="list-group-item">
         Bugatti
         <span class="badge">45</span>
       </a>
       
    </div>
</div>
</div>

</body>
</html>
