<!DOCTYPE html>
<html>
  <head>
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.css" >
    
<style type="text/css">-->
	<link href="/bootstrap-3.3.7/dist/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body { background-color:#DDD; }
      [class*="col"] { margin-bottom: 20px; }
      img { width: 100%; }
      .well {
        background-color:#CCC;
        padding: 20px;
      }
      .inline-form input {
            display: inline-block;
            width: 100px;
        }	
    </style>
  </head>
	<body>
	 <div class="container">
	 
	 <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <ul class="nav navbar-nav">
            <li > <a href="../accueil/">Accueil</a> </li>
            <li> <a href="../add_delete/">Ajout de voiture</a> </li>
            <li class="active"> <a href="">Garage</a> </li>
            
            
          </ul>
          </div>
      </nav>
      
      
      <header class="page-header">
        <h1>Actuellement dans notre garage</h1>
      </header>
	
	<?php 

	foreach($Cars as $Car) {?>
	

	<td>  <B>Propriétaire : </B> <?=$Car->proprietaire ?> </td>

	<td>  <B>Marque : </B> <?=$Car->marque ?> </td>

	<td>  <B>Prix : </B> <?=$Car->prix ?> </td>

	<td>  <B>Date de sortie : </B> <?=$Car->date_sortie ?> </td>
	

	<form method="get" action='/car/add_delete/delete/<?=$Car->id?>' >
	<button type="submit" <span class="glyphicon glyphicon-ok-sign"></span> Supprimer</button>
		<!--<button type="submit"  <span class="glyphicon glyphicon-ok-sign"></span> Modifier</button>-->
	</form>
	<form method="get" action='/car/edit/<?=$Car->id?>' >

		<button type="submit"  <span class="glyphicon glyphicon-ok-sign"></span> Modifier</button>
	</form>
	<?php } ?>
	</div>
	</body>
	</html>
