<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim project</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1></h1>
        <div></div>

        <?php if (isset($name)) : ?>
        <form action="/delete/" method="get">
					<label for="team_name">Enter name: </label>
					<input id="team_name" type="text" name="id" value="Default name for team.">
					<input type="submit" value="OK">
				</form>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try 
				<form action="/delete/" method="get">
					<label for="team_name">Enter name: </label>
					<input id="team_name" type="text" name="id" value="Default name for team.">
					<input type="submit" value="OK">
				</form>
        <?php endif; ?>
    </body>
</html>
